# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import embedder_pb2 as embedder__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbedderServiceStub(object):
    """EmbedderService provides local embedding generation via sentence-transformers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/embedder.EmbedderService/Embed',
                request_serializer=embedder__pb2.EmbedRequest.SerializeToString,
                response_deserializer=embedder__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/embedder.EmbedderService/Info',
                request_serializer=embedder__pb2.InfoRequest.SerializeToString,
                response_deserializer=embedder__pb2.InfoResponse.FromString,
                _registered_method=True)


class EmbedderServiceServicer(object):
    """EmbedderService provides local embedding generation via sentence-transformers.
    """

    def Embed(self, request, context):
        """Embed converts a batch of texts into dense vectors.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Info returns metadata about the loaded model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=embedder__pb2.EmbedRequest.FromString,
                    response_serializer=embedder__pb2.EmbedResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=embedder__pb2.InfoRequest.FromString,
                    response_serializer=embedder__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedder.EmbedderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedder.EmbedderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbedderService(object):
    """EmbedderService provides local embedding generation via sentence-transformers.
    """

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedder.EmbedderService/Embed',
            embedder__pb2.EmbedRequest.SerializeToString,
            embedder__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedder.EmbedderService/Info',
            embedder__pb2.InfoRequest.SerializeToString,
            embedder__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
