# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mbedder.proto\x12\x08\x65mbedder\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"8\n\rEmbedResponse\x12\'\n\nembeddings\x18\x01 \x03(\x0b\x32\x13.embedder.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\r\n\x0bInfoRequest\"0\n\x0cInfoResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x11\n\tdimension\x18\x02 \x01(\x05\x32\x82\x01\n\x0f\x45mbedderService\x12\x38\n\x05\x45mbed\x12\x16.embedder.EmbedRequest\x1a\x17.embedder.EmbedResponse\x12\x35\n\x04Info\x12\x15.embedder.InfoRequest\x1a\x16.embedder.InfoResponseB\x15Z\x13memg/embed/local/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023memg/embed/local/pb'
  _globals['_EMBEDREQUEST']._serialized_start=28
  _globals['_EMBEDREQUEST']._serialized_end=57
  _globals['_EMBEDRESPONSE']._serialized_start=59
  _globals['_EMBEDRESPONSE']._serialized_end=115
  _globals['_EMBEDDING']._serialized_start=117
  _globals['_EMBEDDING']._serialized_end=144
  _globals['_INFOREQUEST']._serialized_start=146
  _globals['_INFOREQUEST']._serialized_end=159
  _globals['_INFORESPONSE']._serialized_start=161
  _globals['_INFORESPONSE']._serialized_end=209
  _globals['_EMBEDDERSERVICE']._serialized_start=212
  _globals['_EMBEDDERSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
