// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: embedder.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmbedderService_Embed_FullMethodName = "/embedder.EmbedderService/Embed"
	EmbedderService_Info_FullMethodName  = "/embedder.EmbedderService/Info"
)

// EmbedderServiceClient is the client API for EmbedderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmbedderService provides local embedding generation via sentence-transformers.
type EmbedderServiceClient interface {
	// Embed converts a batch of texts into dense vectors.
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Info returns metadata about the loaded model.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type embedderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbedderServiceClient(cc grpc.ClientConnInterface) EmbedderServiceClient {
	return &embedderServiceClient{cc}
}

func (c *embedderServiceClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, EmbedderService_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embedderServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, EmbedderService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbedderServiceServer is the server API for EmbedderService service.
// All implementations must embed UnimplementedEmbedderServiceServer
// for forward compatibility.
//
// EmbedderService provides local embedding generation via sentence-transformers.
type EmbedderServiceServer interface {
	// Embed converts a batch of texts into dense vectors.
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Info returns metadata about the loaded model.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedEmbedderServiceServer()
}

// UnimplementedEmbedderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbedderServiceServer struct{}

func (UnimplementedEmbedderServiceServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedEmbedderServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedEmbedderServiceServer) mustEmbedUnimplementedEmbedderServiceServer() {}
func (UnimplementedEmbedderServiceServer) testEmbeddedByValue()                         {}

// UnsafeEmbedderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbedderServiceServer will
// result in compilation errors.
type UnsafeEmbedderServiceServer interface {
	mustEmbedUnimplementedEmbedderServiceServer()
}

func RegisterEmbedderServiceServer(s grpc.ServiceRegistrar, srv EmbedderServiceServer) {
	// If the following call panics, it indicates UnimplementedEmbedderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmbedderService_ServiceDesc, srv)
}

func _EmbedderService_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedderServiceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbedderService_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedderServiceServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbedderService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedderServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbedderService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedderServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbedderService_ServiceDesc is the grpc.ServiceDesc for EmbedderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbedderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "embedder.EmbedderService",
	HandlerType: (*EmbedderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _EmbedderService_Embed_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _EmbedderService_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "embedder.proto",
}
