// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: embedder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_embedder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_embedder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_embedder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{2}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_embedder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{3}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_embedder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{4}
}

func (x *InfoResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *InfoResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

var File_embedder_proto protoreflect.FileDescriptor

const file_embedder_proto_rawDesc = "" +
	"\n" +
	"\x0eembedder.proto\x12\bembedder\"$\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"D\n" +
	"\rEmbedResponse\x123\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x13.embedder.EmbeddingR\n" +
	"embeddings\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\r\n" +
	"\vInfoRequest\"B\n" +
	"\fInfoResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension2\x82\x01\n" +
	"\x0fEmbedderService\x128\n" +
	"\x05Embed\x12\x16.embedder.EmbedRequest\x1a\x17.embedder.EmbedResponse\x125\n" +
	"\x04Info\x12\x15.embedder.InfoRequest\x1a\x16.embedder.InfoResponseB\x15Z\x13memg/embed/local/pbb\x06proto3"

var (
	file_embedder_proto_rawDescOnce sync.Once
	file_embedder_proto_rawDescData []byte
)

func file_embedder_proto_rawDescGZIP() []byte {
	file_embedder_proto_rawDescOnce.Do(func() {
		file_embedder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedder_proto_rawDesc), len(file_embedder_proto_rawDesc)))
	})
	return file_embedder_proto_rawDescData
}

var file_embedder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_embedder_proto_goTypes = []any{
	(*EmbedRequest)(nil),  // 0: embedder.EmbedRequest
	(*EmbedResponse)(nil), // 1: embedder.EmbedResponse
	(*Embedding)(nil),     // 2: embedder.Embedding
	(*InfoRequest)(nil),   // 3: embedder.InfoRequest
	(*InfoResponse)(nil),  // 4: embedder.InfoResponse
}
var file_embedder_proto_depIdxs = []int32{
	2, // 0: embedder.EmbedResponse.embeddings:type_name -> embedder.Embedding
	0, // 1: embedder.EmbedderService.Embed:input_type -> embedder.EmbedRequest
	3, // 2: embedder.EmbedderService.Info:input_type -> embedder.InfoRequest
	1, // 3: embedder.EmbedderService.Embed:output_type -> embedder.EmbedResponse
	4, // 4: embedder.EmbedderService.Info:output_type -> embedder.InfoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_embedder_proto_init() }
func file_embedder_proto_init() {
	if File_embedder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedder_proto_rawDesc), len(file_embedder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedder_proto_goTypes,
		DependencyIndexes: file_embedder_proto_depIdxs,
		MessageInfos:      file_embedder_proto_msgTypes,
	}.Build()
	File_embedder_proto = out.File
	file_embedder_proto_goTypes = nil
	file_embedder_proto_depIdxs = nil
}
